name: Pelican site build and deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
